server:
  port: 9090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zherop/springcloud-demo-config
          search-paths: props
  application:
    name: config-server
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5555/eureka/